const Piadas = () => {
    return [`Sabe qual que é o restaurante que mostra todos os finais de filmes no cardápio?\n\nO SPOILETO`, 
    `Um caipira chega na casa de um amigo que está vendo TV e pergunta:\n-'Firme?'\nE ele responde:\n-'Não, futebor'`,
    `Era uma vez um laboratório que ouvia nirvana. \n\nQual era o nome dele?\n\nKurt Kobaia`,
    `A *plantinha* foi ao hospital, mas não foi atendida.\nPor quê?\n\nPor que lá só tinha médico de *PLANTÃO*`,
    `O que foi que uma impressora falou pra outra? \n\n "Essa folha é sua, ou é impressão minha?"`,
    `Você conhece a piada do fotógrafo?\n\nAinda não foi revelada...`,
    `O que o Buzz Lightyear cristão fala?\n\n"Ao infinito e amém!"`,
    `Sabe por que o tio do Will Smith era muito sentimental?\n\nPor que ele era o tio Feel`,
    `Você sabe qual é o contrário de volátil?\n\nVem cá sobrinho.`,
    `Por que a aranha é o animal mais carente do mundo?\n\nPorque ela é um *aracneedyou*`,
    `Como faz pra passar um elefante por baixo da porta?\nR:Põe ele em um envelope\n\nComo faz pra um elefante *não* passar pela fechadura da porta?\nR:Dá um nó no rabo dele\n\nComo faz pra colocar 5 elefantes num fusca?\nR:2 na frente e 3 atrás.\n\nComo faz pra colocar 5 girafas num outro fusca?\nR:2 na frente, 3 atrás e abre o teto solar.\n\nComo faz pra saber se tem 5 girafas e 5 elefantes num cinema?\nR:Vê se tem 2 fuscas parados na porta.`,
    `Sabe qual é o cantor que largou a carreira pra ser carteiro?\n\nO Zeca Pacotinho`,
    `O que o pato disse para a pata?\nVem Quá!`,
    `A enfermeira diz ao médico:\n-"Tem um homem invisível na sala de espera."\nO médico responde:\n-"Diga a ele que não posso vê-lo agora."`,
    `Era uma vez um pintinho que se chama Relam. Toda vez que chovia, Relam piava!`,
    `No zoológico, um canguru vivia fugindo do cercado. Os tratadores sabiam que ele pulava alto e construíram uma cerca de 3 metros. Não adiantou, porque o canguru sempre fugia. Então, ergueram uma cerca de 6 metros. E ele saiu de novo.\n\nQuando a cerca já estava com 12 metros, o camelo do cercado vizinho perguntou ao canguru:\n- Até que altura você acha que eles vão?\n\nO canguru respondeu:\n-Mais de 300, a menos que alguém tranque o portão à noite.`,
    `Manuel está tomando banho e grita para Maria lhe levar um xampu. Ela leva, mas logo em seguida, o homem grita novamente:\n\n-Ô Maria, me traz outro xampu.\n-Mas eu já te dei um agorinha!\n-É que aqui está dizendo que é para cabelos secos, e eu já molhei os meus.`,
    `Porque o Batman colocou o Bat-móvel no seguro?\nR.: Porque ele tem medo que Robin!`,
    `Qual é o alimento mais sagrado que existe?\nO amém doím.`,
    `Por que o policial não usa sabão?\nPorque ele prefere deter gente.`,
    `Por que a planta não responde?\nPorque ela é mudinha.`,
    `Como se faz omelete de chocolate?\nCom ovos de páscoa.`,
    `O que é um pontinho preto no avião?\nUma aeromosca.`,
    `Qual é a diferença do lago e da padaria?\nNo lago há sapinho e na padaria assa pão.`,
    `Um tênis foi jogado ao mar e afundou. Qual o nome do filme?\nTitanike.`,
    `Um menino tinha um cachorro chamado Tido e ele dormia em um cesto. Um dia, o cachorrinho fugiu, qual é o nome do filme?\nO Cesto sem Tido.`,
    `Por que o pão não entende a batata?\nPorque o pão é francês e a batata é inglesa`,
    `Por que as estrelas não podem ser gatos?\nPorque astro não mia`,
    `Porque coalas não são ursos de verdade?\nPorque eles não têm coalaificação.`,
    `O que a zebra disse para a mosca?\nVocê está na minha listra negra`,
    `Por que na Argentina as vacas vivem olhando para o céu?\nPorque tem boi nos ares!`,
    `Duas vacas estão pastando, quando uma pergunta:\n-Você não tem medo de pegar a doença da vaca louca?\n-Por que teria? Eu sou um helicóptero.`,
    `Três amigos estão conversando e um deles diz:\n-Eu tenho uma piada sobre viagem no tempo, mas não vou contar.\n-Por que não?, o outro pergunta.\n-Porque vocês não gostaram!`,
    `O que o zero disse para o oito?\nBelo cinto!`,
    `O que pediu o astronauta claustrofóbico?\nUm pouco de espaço.`,
    
    ];
}

module.exports = Piadas;